language: node_js
sudo: false

env:
  - SENECA_VER=@1.x.x
  - SENECA_VER=@2.x.x

node_js:
  - "6"
  - "5"
  - "4"
  - "0.10"
  - "0.12"

before_script:
  - if [[ $TRAVIS_NODE_VERSION == "6" ]]; then export LAB_FLAGS="--leaks"; else export LAB_FLAGS=""; fi
  - npm uninstall seneca
  - npm install seneca$SENECA_VER
  - echo FLAGS:$LAB_FLAGS

after_script:
  npm run coverage
